In [2]:
import pandas as pd
# df = pd.read_csv('Confirmed Case.csv')
df = pd.read_excel('File Name.xlsx')

df.head()
# df.to_excel(r'FileName.xlsx', sheet_name='Sheet1')

Date  Aceh  Bali  Banten  Babel  Bengkulu  DIY  Jakarta  Jambi  \
0  2020-03-15     0     0       0      0         0    0       19      0   
1  2020-03-16     0     0       1      0         0    0       14      0   
2  2020-03-17     0     0       0      0         0    0        0      0   
3  2020-03-18     0     0       4      0         0    1       30      0   
4  2020-03-19     0     0      10      0         0    2       52      0   

   Jabar  ...  Sulteng  Lampung  Riau  Malut  Maluku  Papbar  Papua  Sulbar  \
0      0  ...        0        0     0      0       0       0      0       0   
1      1  ...        0        0     0      0       0       0      0       0   
2      0  ...        0        0     0      0       0       0      0       0   
3     12  ...        0        1     1      0       0       0      0       0   
4      2  ...        0        0     1      0       0       0      0       0   

   NTT  Gorontalo  
0    0          0  
1    0          0  
2    0          0  
3    0          0  
4    0          0  

[5 rows x 35 columns]

In [72]:
df.insert(loc=1, column='Total Kasus', value=df.sum(axis = 1, skipna = True))
df.tail()

C:\Users\yusri\AppData\Local\Temp\ipykernel_85404\2004861988.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.insert(loc=1, column='Total Kasus', value=df.sum(axis = 1, skipna = True))


Date  Total Kasus  Aceh  Bali  Banten  Babel  Bengkulu  \
864  2022-07-27 00:00:00         6430     7   172     757      9         0   
865  2022-07-28 00:00:00         6354     0   222     745      6         0   
866  2022-07-29 00:00:00         5834     6   140     717      5         0   
867  2022-07-30 00:00:00         5400     0   161     626      1         0   
868  2022-07-31 00:00:00         4205     0   111     543      0         2   

     DIY  Jakarta  Jambi  ...  Sulteng  Lampung  Riau  Malut  Maluku  Papbar  \
864  121     3279      3  ...        0       11    13      0       5       5   
865   72     3157      6  ...        2        2    53      2       3       8   
866   89     2987      5  ...        3        2    21      0       6       7   
867   85     2629      2  ...        2       14    25      1       2       8   
868   49     2198      0  ...        0       14    33      0       1       0   

     Papua  Sulbar  NTT  Gorontalo  
864     32       1    7          6  
865     22       0    0          1  
866     23       2    4          2  
867     13       0    9          1  
868     12       1    3          2  

[5 rows x 36 columns]

In [33]:
clean = df.T.to_csv('Confirmed Case Clean.csv', header=False)

In [64]:
df.fillna(0, inplace = True)
df.tail()

Date  Total Kasus  Aceh  Bali  Banten  Babel  Bengkulu  \
864  2022-07-27 00:00:00         6430     7   172     757      9         0   
865  2022-07-28 00:00:00         6354     0   222     745      6         0   
866  2022-07-29 00:00:00         5834     6   140     717      5         0   
867  2022-07-30 00:00:00         5400     0   161     626      1         0   
868  2022-07-31 00:00:00         4205     0   111     543      0         2   

     DIY  Jakarta  Jambi  ...  Sulteng  Lampung  Riau  Malut  Maluku  Papbar  \
864  121     3279      3  ...        0       11    13      0       5       5   
865   72     3157      6  ...        2        2    53      2       3       8   
866   89     2987      5  ...        3        2    21      0       6       7   
867   85     2629      2  ...        2       14    25      1       2       8   
868   49     2198      0  ...        0       14    33      0       1       0   

     Papua  Sulbar  NTT  Gorontalo  
864     32       1    7          6  
865     22       0    0          1  
866     23       2    4          2  
867     13       0    9          1  
868     12       1    3          2  

[5 rows x 36 columns]

In [ ]:
df.info()

In [32]:
df.head()
# df.to_excel(r'File Name.xlsx', sheet_name='Your sheet name')

Date  Total Kasus  Aceh  Bali  Banten  Babel  Bengkulu  DIY  Jakarta  \
0  2020-03-15           21     0     0       0      0         0    0       19   
1  2020-03-16           17     0     0       1      0         0    0       14   
2  2020-03-17            0     0     0       0      0         0    0        0   
3  2020-03-18           53     0     0       4      0         0    1       30   
4  2020-03-19           82     0     0      10      0         0    2       52   

   Jambi  ...  Sulteng  Lampung  Riau  Malut  Maluku  Papbar  Papua  Sulbar  \
0      0  ...        0        0     0      0       0       0      0       0   
1      0  ...        0        0     0      0       0       0      0       0   
2      0  ...        0        0     0      0       0       0      0       0   
3      0  ...        0        1     1      0       0       0      0       0   
4      0  ...        0        0     1      0       0       0      0       0   

   NTT  Gorontalo  
0    0          0  
1    0          0  
2    0          0  
3    0          0  
4    0          0  

[5 rows x 36 columns]

In [3]:
df = pd.read_csv('Confirmed Case Clean.csv')
df.head()

Date  2020-03-15  2020-03-16  2020-03-17  2020-03-18  2020-03-19  \
0  Total Kasus          21          17           0          53          82   
1         Aceh           0           0           0           0           0   
2         Bali           0           0           0           0           0   
3       Banten           0           1           0           4          10   
4        Babel           0           0           0           0           0   

   2020-03-20  2020-03-21  2020-03-22  2020-03-23  ...  2022-07-22  \
0          47          78          64          61  ...        4833   
1           0           0           0           0  ...           0   
2           3           0           0           3  ...         158   
3          10           4           0           9  ...         550   
4           0           0           0           0  ...           5   

   2022-07-23  2022-07-24  2022-07-25  2022-07-26  2022-07-27  2022-07-28  \
0        4940        4066        4043        6464        6430        6354   
1           0           0           1           0           7           0   
2         175         149         132         228         172         222   
3         553         467         533         949         757         745   
4           7           3           5          17           9           6   

   2022-07-29  2022-07-30  2022-07-31  
0        5834        5400        4205  
1           6           0           0  
2         140         161         111  
3         717         626         543  
4           5           1           0  

[5 rows x 870 columns]

In [5]:
import numpy as np

dates = df.columns.values[1:]
days_since = np.array([i for i in range(len(dates))]).reshape(-1,1)

In [6]:
daysinfuture = 49
future_forecast = np.array([i for i in range(len(dates)+daysinfuture)]).reshape(-1,1)
adjusted_dates = future_forecast[:-49]

In [8]:
import datetime

start = '3-18-2020'
start_date = datetime.datetime.strptime(start, '%m-%d-%Y')
future_forecast_dates = []
for i in range(len(future_forecast)):
    future_forecast_dates.append((start_date + datetime.timedelta(days = i)).strftime('%m/%d/%Y'))

In [9]:
cases = df.iloc[0,:].values[1:]
total_cases = np.array(cases).reshape(-1,1)

In [10]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(days_since,total_cases, test_size = 0.3, shuffle = False)

In [11]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree = 3)
polyx = poly.fit_transform(days_since)
polyforecast = poly.transform(future_forecast)
polyxtest= poly.transform(xtest)

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

lr = LinearRegression(fit_intercept = False)
lr.fit(polyx, total_cases)
ypred = lr.predict(polyxtest)
ypredforecast = lr.predict(polyforecast)
r2 = r2_score(ytest,ypred)
print(r2, 'Done')
print(future_forecast)

0.03902892047829554 Done
[[  0]
 [  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]
 [ 12]
 [ 13]
 [ 14]
 [ 15]
 [ 16]
 [ 17]
 [ 18]
 [ 19]
 [ 20]
 [ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [ 30]
 [ 31]
 [ 32]
 [ 33]
 [ 34]
 [ 35]
 [ 36]
 [ 37]
 [ 38]
 [ 39]
 [ 40]
 [ 41]
 [ 42]
 [ 43]
 [ 44]
 [ 45]
 [ 46]
 [ 47]
 [ 48]
 [ 49]
 [ 50]
 [ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 56]
 [ 57]
 [ 58]
 [ 59]
 [ 60]
 [ 61]
 [ 62]
 [ 63]
 [ 64]
 [ 65]
 [ 66]
 [ 67]
 [ 68]
 [ 69]
 [ 70]
 [ 71]
 [ 72]
 [ 73]
 [ 74]
 [ 75]
 [ 76]
 [ 77]
 [ 78]
 [ 79]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 85]
 [ 86]
 [ 87]
 [ 88]
 [ 89]
 [ 90]
 [ 91]
 [ 92]
 [ 93]
 [ 94]
 [ 95]
 [ 96]
 [ 97]
 [ 98]
 [ 99]
 [100]
 [101]
 [102]
 [103]
 [104]
 [105]
 [106]
 [107]
 [108]
 [109]
 [110]
 [111]
 [112]
 [113]
 [114]
 [115]
 [116]
 [117]
 [118]
 [119]
 [120]
 [121]
 [122]
 [123]
 [124]
 [125]
 [126]
 [127]
 [128]
 [129]
 [130]
 [131]
 [132]
 [133]
 [134]
 [135]
 [136]
 [137]
 [138]
 [

In [24]:
DON RUN!!!!!
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import r2_score

# lr = LinearRegression(fit_intercept = False)
# lr.fit(polyx, total_cases)
# ypred = lr.predict(polyxtest)
# ypredforecast = lr.predict(polyforecast)
# r2 = r2_score(ytest,ypred)
# print(r2, 'Done')
# print(future_forecast)

0.924587280128041 Done
[[  0]
 [  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]
 [ 12]
 [ 13]
 [ 14]
 [ 15]
 [ 16]
 [ 17]
 [ 18]
 [ 19]
 [ 20]
 [ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [ 30]
 [ 31]
 [ 32]
 [ 33]
 [ 34]
 [ 35]
 [ 36]
 [ 37]
 [ 38]
 [ 39]
 [ 40]
 [ 41]
 [ 42]
 [ 43]
 [ 44]
 [ 45]
 [ 46]
 [ 47]
 [ 48]
 [ 49]
 [ 50]
 [ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 56]
 [ 57]
 [ 58]
 [ 59]
 [ 60]
 [ 61]
 [ 62]
 [ 63]
 [ 64]
 [ 65]
 [ 66]
 [ 67]
 [ 68]
 [ 69]
 [ 70]
 [ 71]
 [ 72]
 [ 73]
 [ 74]
 [ 75]
 [ 76]
 [ 77]
 [ 78]
 [ 79]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 85]
 [ 86]
 [ 87]
 [ 88]
 [ 89]
 [ 90]
 [ 91]
 [ 92]
 [ 93]
 [ 94]
 [ 95]
 [ 96]
 [ 97]
 [ 98]
 [ 99]
 [100]
 [101]
 [102]
 [103]
 [104]
 [105]
 [106]
 [107]
 [108]
 [109]
 [110]
 [111]
 [112]
 [113]
 [114]
 [115]
 [116]
 [117]
 [118]
 [119]
 [120]
 [121]
 [122]
 [123]
 [124]
 [125]
 [126]
 [127]
 [128]
 [129]
 [130]
 [131]
 [132]
 [133]
 [134]
 [135]
 [136]
 [137]
 [138]
 [13

In [13]:
test1 = [[214]] 
test2 = poly.transform(test1)
print(test2)
pred11 = lr.predict(test2)
print(pred11)

[[1.000000e+00 2.140000e+02 4.579600e+04 9.800344e+06]]
[[4724.30924649]]


In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Columns: 870 entries, Date to 2022-07-31
dtypes: int64(869), object(1)
memory usage: 238.0+ KB


In [14]:
import pickle

pickle.dump(lr, open('pred.pkl', 'wb'))
pickle.dump(poly, open('transform.pkl', 'wb'))

In [55]:
from sklearn.preprocessing import PolynomialFeatures
for i in range(1,35):
    cases = df.iloc[i,:].values[1:]
    total_cases = np.array(cases).reshape(-1,1)
    
    xtrain,xtest,ytrain,ytest = train_test_split(days_since,total_cases, test_size = 0.3, shuffle = False)
    finalforecast = []
    tempr2 = 0
    temp = 0
    for j in range(2,4):
        poly = PolynomialFeatures(degree = j)
        polyx = poly.fit_transform(days_since)
        polyforecast = poly.transform(future_forecast)
        polyxtest= poly.transform(xtest)
        

        lr = LinearRegression(fit_intercept = False)#
        lr.fit(polyx, total_cases)
        ypred = lr.predict(polyxtest)
        ypredforecast = lr.predict(polyforecast)
        r2 = r2_score(ytest,ypred)
        
        if r2 > tempr2:
            tempr2 = r2
            finalforecast = ypredforecast
            temp = j
            
        if tempr2 ==0:
            lr2 = LinearRegression(fit_intercept = False)
            lr2.fit(days_since,total_cases)
            ypred = lr2.predict(xtest)
            finalforecast = lr2.predict(future_forecast)
            r2 = r2_score(ytest,ypred)
            
    if i == 1:
        pickle.dump(lr, open('ac.pkl', 'wb'))
    elif i ==2:
        pickle.dump(lr, open('bl.pkl', 'wb'))
    elif i ==3:
        pickle.dump(lr, open('btn.pkl', 'wb'))
    elif i ==4:
        pickle.dump(lr, open('bbl.pkl', 'wb'))
    elif i ==5:
        pickle.dump(lr, open('bngk.pkl', 'wb'))
    elif i ==6:
        pickle.dump(lr, open('diy.pkl', 'wb'))
    elif i ==7:
        pickle.dump(lr, open('jkt.pkl', 'wb'))
    elif i ==8:
        pickle.dump(lr, open('jmb.pkl', 'wb'))
    elif i ==9:
        pickle.dump(lr, open('jbr.pkl', 'wb'))
    elif i ==10:
        pickle.dump(lr, open('jtn.pkl', 'wb'))
    elif i ==11:
        pickle.dump(lr, open('jtm.pkl', 'wb'))
    elif i ==12:
        pickle.dump(lr, open('klbr.pkl', 'wb'))
    elif i ==13:
        pickle.dump(lr, open('kltm.pkl', 'wb'))
    elif i ==14:
        pickle.dump(lr, open('kltng.pkl', 'wb'))  
    elif i ==15:
        pickle.dump(lr, open('klsl.pkl', 'wb'))
    elif i ==16:
        pickle.dump(lr, open('kltu.pkl', 'wb'))
    elif i ==17:
        pickle.dump(lr, open('kria.pkl', 'wb'))
    elif i ==18:
        pickle.dump(lr, open('ntb.pkl', 'wb'))
    elif i ==19:
        pickle.dump(lr, open('smsl.pkl', 'wb'))
    elif i ==20:
        pickle.dump(lr, open('smbr.pkl', 'wb'))
    elif i ==21:
        pickle.dump(lr, open('slt.pkl', 'wb'))
    elif i ==22:
        pickle.dump(lr, open('smut.pkl', 'wb'))
    elif i ==23:
        pickle.dump(lr, open('sltr.pkl', 'wb'))
    elif i ==24:
        pickle.dump(lr, open('slsl.pkl', 'wb'))
    elif i ==25:
        pickle.dump(lr, open('sltg.pkl', 'wb'))
    elif i ==26:
        pickle.dump(lr, open('lmpg.pkl', 'wb'))
    elif i ==27:
        pickle.dump(lr, open('ria.pkl', 'wb'))
    elif i ==28:
        pickle.dump(lr, open('malut.pkl', 'wb'))
    elif i ==29:
        pickle.dump(lr, open('mlku.pkl', 'wb'))
    elif i ==30:
        pickle.dump(lr, open('papbr.pkl', 'wb'))
    elif i ==31:
        pickle.dump(lr, open('ppa.pkl', 'wb'))
    elif i ==32:
        pickle.dump(lr, open('slbr.pkl', 'wb'))
    elif i ==33:
        pickle.dump(lr, open('ntt.pkl', 'wb'))
    elif i ==34:
        pickle.dump(lr, open('grtl.pkl', 'wb'))
    else:
        pickle.dump(lr, open('none.pkl', 'wb'))

In [ ]:
import numpy as np

actual = np.array([1100,2000,550,1510,2000])
prediction = np.array([1000,2000,500,1500,3000])

rmse = np.sqrt(np.mean((prediction-actual)**2))
print(rmse)